### ISSUE TITLE
Not working on latest Adobe XD version

### ISSUE THREAD

**Issue by quantumleap33** [realvjy/uilogos-XD#2]
It doesn't seem to work on the January XD release at least. Once you click Control+Shift+F, the rectangle shapes are not selectable and once the OK button is clicked nothing happens.

On PC, Windows 10 here.

**Comment by realvjy** [comment]
@quantumleap33 Thank you for reporting this issue. It's working on the last version (16.0.2.8) of macOS though.

 Can you please share XD version? Did you check directly from the menu? Reinstall plugin again. The short cut key may be occupied by another plugin.

**Comment by quantumleap33** [comment]
@realvjy  I use XD on Win10. I did everything, installed reinstalled and tried not to use a shortcut. As I said though, the problem is not the shortcut, the window opens up, it's just that you cannot proceed after the initial window, the rectangles are not clickable. All you are left to do is click OK and that's it, nothing happens. I use the latest February version, 16.0.2.8.

**Comment by realvjy** [comment]
@quantumleap33 I tested on the updated win10. There is not an issue with the plugin. 

Closing this issue.
